/**
 * Created by lqq.li on 15/11/25.
 */
module.exports = {
    ret: true,
    errcode: 0,
    msg: "",
    data: {
        total: 148,
        currPage: 1,
        processUrl: 'http://l-intertaxi3.wap.dev.cn0.qunar.com:9028/support/flight/freeGift',
        list: [
            {
                id: 170,
                activityCode: "0",
                sort: 0,
                totalCount: 0,
                prizeCode: "888",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-07",
                prizeDesc: "机票免单"
            },
            {
                id: 117933,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "804",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "QQ阅读"
            },
            {
                id: 50895,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "802",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "趣游宝佣金"
            },
            {
                id: 50894,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "801",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "度假代金券"
            },
            {
                id: 50893,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "802",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "趣游宝佣金"
            },
            {
                id: 50892,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "802",
                userName: "bhvjonq8489",
                prizeStatus: 1,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "趣游宝佣金"
            },
            {
                id: 50891,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "804",
                userName: "bhvjonq8489",
                prizeStatus: 1,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "QQ阅读"
            },
            {
                id: 50890,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "802",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "趣游宝佣金"
            },
            {
                id: 50889,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "801",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "度假代金券"
            },
            {
                id: 50888,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "801",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "度假代金券"
            },
            {
                id: 50887,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "804",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "QQ阅读"
            },
            {
                id: 50886,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "802",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-11",
                prizeDesc: "趣游宝佣金"
            },
            {
                id: 30752,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "801",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-09",
                prizeDesc: "度假代金券"
            },
            {
                id: 30751,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "804",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-09",
                prizeDesc: "QQ阅读"
            },
            {
                id: 30750,
                activityCode: "Spring Festival lottery",
                sort: 1,
                totalCount: 0,
                prizeCode: "804",
                userName: "bhvjonq8489",
                prizeStatus: 0,
                repeat: false,
                chance: 0,
                ctime: "2016-01-09",
                prizeDesc: "QQ阅读"
            }
        ],
        totalPage: 10
    }
}