module.exports = {
    "ret": true,
    "errcode": 0,
    "msg": "",
    "data": {
        phone: "010-88869999",
        desc: "北京美泉宫饭店坐落于京城西部，是北京城里罕有的温泉饭店。饭店的建筑体现浓郁的巴洛克风格，内饰精致尊贵，外观古典恢弘。美泉宫饭店位于高速发展的西四环地区的四季青桥南侧，从饭店到机场用时仅为30分钟，到奥运鸟巢及水立方仅耗时20分钟。饭店一期（北楼）拥有不同类型客房344间，大小不同会议室12间，其中国际厅可容纳450人。饭店配有新派潮粤口味的汇泉轩中餐厅、阳光花园西餐厅、大堂水晶吧，以及商务中心、精品购物商场、健身房、台球室、游泳池、温泉SPA养生馆、专业中医推拿、美容美发和大型停车场等众多服务设施。",
        rnum: "344",
        facilities: [
            {
                datas: [
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasWifiInRoom.png",
                        overseasSort: 3,
                        display: true,
                        lowStarSort: 1,
                        type: "网络设施",
                        highStarSort: 1,
                        field: "hasWifiInRoom",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasWifiInRoom_big.png",
                        color: -14964294,
                        item: "房间wifi",
                        shortName: "房间wifi",
                        oldVersionFilter: true
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/WifiAccess.png",
                        overseasSort: 3,
                        display: true,
                        lowStarSort: 1,
                        type: "网络设施",
                        highStarSort: 1,
                        field: "WifiAccess",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/WifiAccess_big.png",
                        color: -14964294,
                        item: "公共区域wifi",
                        shortName: "公共wifi",
                        oldVersionFilter: true
                    },
                    {
                        desc: "(免费)",
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/isWebFree.png",
                        overseasSort: 3,
                        display: true,
                        lowStarSort: 1,
                        type: "网络设施",
                        highStarSort: 1,
                        field: "HasInternetAccess",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/isWebFree_big.png",
                        color: -14964294,
                        item: "宽带上网",
                        shortName: "宽带上网",
                        oldVersionFilter: true
                    }
                ],
                type: "网络设施"
            },
            {
                datas: [
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/has24hotwater.png",
                        overseasSort: 29,
                        display: true,
                        lowStarSort: 2,
                        type: "房间设施",
                        highStarSort: 29,
                        field: "has24hotwater",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/has24hotwater_big.png",
                        color: -14964294,
                        item: "全天热水",
                        shortName: "全天热水",
                        oldVersionFilter: true
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasHairDryer.png",
                        overseasSort: 30,
                        display: true,
                        lowStarSort: 4,
                        type: "房间设施",
                        highStarSort: 30,
                        field: "HasHairDryer",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasHairDryer_big.png",
                        color: -14964294,
                        item: "吹风机",
                        shortName: "吹风机",
                        oldVersionFilter: true
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasAirConditioning.png",
                        overseasSort: 32,
                        display: true,
                        lowStarSort: 3,
                        type: "房间设施",
                        highStarSort: 32,
                        field: "HasAirConditioning",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasAirConditioning_big.png",
                        color: -14964294,
                        item: "空调",
                        shortName: "空调",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasInternationalPhoneCall.png",
                        overseasSort: 34,
                        display: true,
                        lowStarSort: 22,
                        type: "房间设施",
                        highStarSort: 34,
                        field: "hasInternationalPhoneCall",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasInternationalPhoneCall_big.png",
                        color: -14964294,
                        item: "国际长途电话",
                        shortName: "国际长途",
                        oldVersionFilter: false
                    }
                ],
                type: "房间设施"
            },
            {
                datas: [
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasElevator.png",
                        overseasSort: 35,
                        display: true,
                        lowStarSort: 9,
                        type: "通用设施",
                        highStarSort: 35,
                        field: "hasElevator",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasElevator_big.png",
                        color: -14964294,
                        item: "电梯",
                        shortName: "电梯",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasFitnessRoom.png",
                        overseasSort: 4,
                        display: true,
                        lowStarSort: 29,
                        type: "通用设施",
                        highStarSort: 2,
                        field: "HasFitnessRoom",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasFitnessRoom_big.png",
                        color: -14964294,
                        item: "健身房",
                        shortName: "健身房",
                        oldVersionFilter: true
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasSauna.png",
                        overseasSort: 8,
                        display: true,
                        lowStarSort: 33,
                        type: "通用设施",
                        highStarSort: 8,
                        field: "HasSauna",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasSauna_big.png",
                        color: -14964294,
                        item: "桑拿",
                        shortName: "桑拿",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasChineseRestaurant.png",
                        overseasSort: 10,
                        display: true,
                        lowStarSort: 8,
                        type: "通用设施",
                        highStarSort: 10,
                        field: "hasChineseRestaurant",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasChineseRestaurant_big.png",
                        color: -14964294,
                        item: "中式餐厅",
                        shortName: "中式餐厅",
                        oldVersionFilter: true
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasDisabledRoom.png",
                        overseasSort: 23,
                        display: true,
                        lowStarSort: 42,
                        type: "通用设施",
                        highStarSort: 23,
                        field: "hasDisabledRoom",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasDisabledRoom_big.png",
                        color: -14964294,
                        item: "残疾人客房",
                        shortName: "残疾人房",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasPub.png",
                        overseasSort: 15,
                        display: true,
                        lowStarSort: 31,
                        type: "通用设施",
                        highStarSort: 15,
                        field: "hasPub",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasPub_big.png",
                        color: -14964294,
                        item: "酒吧",
                        shortName: "酒吧",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasNonSmokingAvailable.png",
                        overseasSort: 17,
                        display: true,
                        lowStarSort: 14,
                        type: "通用设施",
                        highStarSort: 17,
                        field: "HasNonSmokingAvailable",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasNonSmokingAvailable_big.png",
                        color: -14964294,
                        item: "无烟房",
                        shortName: "无烟房",
                        oldVersionFilter: true
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasParkingArea2.png",
                        overseasSort: 20,
                        display: true,
                        lowStarSort: 6,
                        type: "通用设施",
                        highStarSort: 20,
                        field: "hasParkingArea2",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasParkingArea2_big.png",
                        color: -14964294,
                        item: "免费停车",
                        shortName: "停车场",
                        oldVersionFilter: true
                    }
                ],
                type: "通用设施"
            },
            {
                datas: [
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasTaxiService.png",
                        overseasSort: 7,
                        display: true,
                        lowStarSort: 37,
                        type: "服务项目",
                        highStarSort: 5,
                        field: "hasTaxiService",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasTaxiService_big.png",
                        color: -14964294,
                        item: "叫车服务",
                        shortName: "叫车服务",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasCarRent.png",
                        overseasSort: 14,
                        display: true,
                        lowStarSort: 27,
                        type: "服务项目",
                        highStarSort: 14,
                        field: "hasCarRent",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasCarRent_big.png",
                        color: -14964294,
                        item: "租车",
                        shortName: "租车",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasHandicApaccessible.png",
                        overseasSort: 22,
                        display: true,
                        lowStarSort: 34,
                        type: "服务项目",
                        highStarSort: 22,
                        field: "HasHandicApaccessible",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasHandicApaccessible_big.png",
                        color: -14964294,
                        item: "残疾人设施",
                        shortName: "残疾设施",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasMeetingORBanquetSpace.png",
                        overseasSort: 18,
                        display: true,
                        lowStarSort: 19,
                        type: "服务项目",
                        highStarSort: 18,
                        field: "HasMeetingORBanquetSpace",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasMeetingORBanquetSpace_big.png",
                        color: -14964294,
                        item: "会议室",
                        shortName: "会议室",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasGuestLaundromat.png",
                        overseasSort: 21,
                        display: true,
                        lowStarSort: 18,
                        type: "服务项目",
                        highStarSort: 21,
                        field: "HasGuestLaundromat",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasGuestLaundromat_big.png",
                        color: -14964294,
                        item: "洗衣服务",
                        shortName: "洗衣服务",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasBusinessCenter.png",
                        overseasSort: 27,
                        display: true,
                        lowStarSort: 21,
                        type: "服务项目",
                        highStarSort: 27,
                        field: "HasBusinessCenter",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasBusinessCenter_big.png",
                        color: -14964294,
                        item: "商务中心",
                        shortName: "商务中心",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasWakeUpService.png",
                        overseasSort: 28,
                        display: true,
                        lowStarSort: 12,
                        type: "服务项目",
                        highStarSort: 28,
                        field: "HasWakeUpService",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasWakeUpService_big.png",
                        color: -14964294,
                        item: "唤醒服务",
                        shortName: "唤醒服务",
                        oldVersionFilter: true
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasLeftLuggage.png",
                        overseasSort: 31,
                        display: true,
                        lowStarSort: 5,
                        type: "服务项目",
                        highStarSort: 31,
                        field: "hasLeftLuggage",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasLeftLuggage_big.png",
                        color: -14964294,
                        item: "行李寄存",
                        shortName: "行李寄存",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/creditCard.png",
                        overseasSort: 33,
                        display: true,
                        lowStarSort: 13,
                        type: "服务项目",
                        highStarSort: 33,
                        field: "creditCard",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/creditCard_big.png",
                        color: -14964294,
                        item: "信用卡服务",
                        shortName: "信用卡",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasReceiveVisitor.png",
                        overseasSort: 37,
                        display: true,
                        lowStarSort: 17,
                        type: "服务项目",
                        highStarSort: 37,
                        field: "hasReceiveVisitor",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasReceiveVisitor_big.png",
                        color: -14964294,
                        item: "接待外宾",
                        shortName: "接待外宾",
                        oldVersionFilter: false
                    }
                ],
                type: "服务项目"
            },
            {
                datas: [
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/hasSPA.png",
                        overseasSort: 2,
                        display: true,
                        lowStarSort: 32,
                        type: "活动设施",
                        highStarSort: 7,
                        field: "hasSPA",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/hasSPA_big.png",
                        color: -14964294,
                        item: "SPA",
                        shortName: "SPA",
                        oldVersionFilter: false
                    },
                    {
                        iconUrl: "http://source.qunar.com/site/images/wap/servicesv1/HasChessRoom.png",
                        overseasSort: 19,
                        display: true,
                        lowStarSort: 25,
                        type: "活动设施",
                        highStarSort: 19,
                        field: "HasChessRoom",
                        iconBig: "http://source.qunar.com/site/images/wap/servicesv1/HasChessRoom_big.png",
                        color: -14964294,
                        item: "棋牌室",
                        shortName: "棋牌室",
                        oldVersionFilter: false
                    }
                ],
                type: "活动设施"
            }
        ]
    }
};
