// module.exports = {
//     "ret": true,
//     "errcode": 0,
//     "msg": "",
//     "data": {
//         "minPrice": 0,
//         "totalPage": 0,
//         "hotels": []
//     }
// };

// return;
module.exports = {
    "ret": true,
    "errcode": 0,
    "msg": "",
    "data": {
        "minPrice": 474,
        "totalPage": 20,
        "hotels": [{

            "price": "245",
            "mobilePrice": "245",
            "isLM": "0",
            "id": "beijing_city_1917",
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "238",
                "isCwt": "",
                "CommentScore": "4.4",
                "isTop500": "",
                "gpoint": "39.909904,116.40622",
                "HasInternetAccess": "免费",
                "CommentCount": "2257",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201201/11/JhS1_t5QMXUTrjlQJ120.jpg",
                "whenFitment": "2012",
                "hotelAddress": "北京市东城区南河沿大街南湾子胡同1号",
                "theme": "",
                "WhenBuilt": "2007",
                "HotelArea": "东城区",
                "PolicyInfo": "",
                "tradingArea": "王府井商圈|前门商圈",
                "hotelName": "北京香江戴斯酒店",
                "nearAddress": "在天安门东地铁站B口附近",
                "dangci": "2",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "distance": "0",
            "showAddr": "王府井商圈|前门商圈, 在天安门东地铁站B口附近",
            "cityName": "北京",
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],

            "mobileRoomStatus": 2
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "169",
            "qualityLabelList": [{
                "rawType": 3,
                "frameColor": 0,
                "type": 2,
                "content": "人气热卖!",
                "fontColor": 0
            }],
            "topList": 0,
            "mobilePrice": "169",
            "isLM": "1",
            "id": "beijing_city_23592",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [{
                "labelContent": "人气热卖!",
                "labelType": 3
            }],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "-1",
                "isCwt": "",
                "CommentScore": "4.4",
                "isTop500": "",
                "gpoint": "40.061573,116.58519",
                "HasInternetAccess": "免费",
                "CommentCount": "1947",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201511/18/66I5P257CSuNqI6M6120.jpg",
                "whenFitment": "2014",
                "hotelAddress": "北京顺义区天竺镇天竺中街4号（靠近新国展及航站楼）",
                "theme": "",
                "WhenBuilt": "2014",
                "HotelArea": "顺义区",
                "PolicyInfo": "",
                "tradingArea": "首都机场",
                "hotelName": "格林豪泰北京市首都机场第二快捷酒店",
                "nearAddress": "",
                "dangci": "1",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "hta0000135b": "6",
                "wapqtalm000": "14",
                "hta0000135a": "6",
                "wapqunarqta": "30"
            },
            "showRetureGold": false,
            "lmLowestPrice": true,
            "hasGroupBuy": true,
            "rankInfo": 4098,
            "logicBit": 2359552,
            "activity": 65536,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "首都机场",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": false,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": false,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 3,
            "specialPriceBit": 2496,
            "hasExclusive": true,
            "hasGift": false,
            "mobileRoomStatus": 1,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "194",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "185",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "185",
            "isLM": "0",
            "id": "beijing_city_34211",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "N",
                "MiniRetailPrice": "199",
                "isCwt": "",
                "CommentScore": "4.7",
                "isTop500": "",
                "gpoint": "40.207718,116.23369",
                "HasInternetAccess": "无",
                "CommentCount": "167",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201508/24/66I5P25_YPt0gVt96120.jpg",
                "whenFitment": "2015",
                "hotelAddress": "北京昌平区振兴路9号（近中国石油大学成人学院）",
                "theme": "",
                "WhenBuilt": "2015",
                "HotelArea": "昌平区",
                "PolicyInfo": "",
                "tradingArea": "",
                "hotelName": "北京神舟商旅酒店昌平店",
                "nearAddress": "",
                "dangci": "2",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "hta0989310a": "6",
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": true,
            "rankInfo": 1,
            "logicBit": 3760455940,
            "activity": 167837696,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "北京昌平区振兴路9号（近中国石油大学成人学院）",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": true,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": true,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 2,
            "specialPriceBit": 2496,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 2,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "2147483647",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "271",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "271",
            "isLM": "1",
            "id": "beijing_city_17934",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "188",
                "isCwt": "",
                "CommentScore": "4.6",
                "isTop500": "",
                "gpoint": "39.938526,116.39735",
                "HasInternetAccess": "免费",
                "CommentCount": "498",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201407/01/LOLoxmAz736x9s79r120.jpg",
                "whenFitment": "2015",
                "hotelAddress": "北京市东城区鼓楼辛安里66号（近鼓楼、后海、地铁什刹海A2口出）",
                "theme": "",
                "WhenBuilt": "2011",
                "HotelArea": "东城区",
                "PolicyInfo": "",
                "tradingArea": "后海、什刹海|东直门商圈",
                "hotelName": "北京乐盟酒店",
                "nearAddress": "与什刹海地铁站A2口相邻",
                "dangci": "5",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "2"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "wapqtalm000": "14",
                "hta1150890a": "7",
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": true,
            "hasGroupBuy": false,
            "rankInfo": 3,
            "logicBit": 3758358788,
            "activity": 65536,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "后海、什刹海|东直门商圈, 与什刹海地铁站A2口相邻",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": true,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": true,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 1,
            "specialPriceBit": 384,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 1,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }],
            "lmPrice": "271",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "268",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "268",
            "isLM": "1",
            "id": "beijing_city_27291",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "-1",
                "isCwt": "",
                "CommentScore": "4.5",
                "isTop500": "",
                "gpoint": "40.130203,116.61575",
                "HasInternetAccess": "免费",
                "CommentCount": "433",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201508/21/JhS1_thDfS1xtIoSJ120.jpg",
                "whenFitment": "2014",
                "hotelAddress": "北京市顺义区南法信南陈路35号",
                "theme": "",
                "WhenBuilt": "2014",
                "HotelArea": "顺义区",
                "PolicyInfo": "",
                "tradingArea": "顺义温泉休闲区",
                "hotelName": "北京航港之佳大酒店",
                "nearAddress": "在南法信地铁站B口附近",
                "dangci": "3",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "wiqunarqta2": "6",
                "wapqtalm000": "6",
                "wiqtaota002": "6",
                "hta0000358a": "6",
                "wiqtalm0000": "6",
                "hta0989310a": "6",
                "hta1150890a": "6",
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": false,
            "rankInfo": 8388609,
            "logicBit": 3758358788,
            "activity": 176226304,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "顺义温泉休闲区, 在南法信地铁站B口附近",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": true,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": true,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 1,
            "specialPriceBit": 1920,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 1,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "268",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "338",
            "qualityLabelList": [{
                "rawType": 3,
                "frameColor": 0,
                "type": 2,
                "content": "人气热卖!",
                "fontColor": 0
            }],
            "topList": 0,
            "mobilePrice": "338",
            "isLM": "0",
            "id": "beijing_city_2648",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": true,
            "corrDist": "",
            "hotelLabel": [{
                "labelContent": "人气热卖!",
                "labelType": 3
            }],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "232",
                "isCwt": "",
                "CommentScore": "4.6",
                "isTop500": "",
                "gpoint": "39.938885,116.44487",
                "HasInternetAccess": "免费",
                "CommentCount": "856",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201509/16/66I5P25oJ2seTmoz6120.jpg",
                "whenFitment": "2014",
                "hotelAddress": "北京市朝阳区东直门外大街春秀路太平庄10号（紧邻东直门外大街及工人体育场）",
                "theme": "",
                "WhenBuilt": "2008",
                "HotelArea": "朝阳区",
                "PolicyInfo": "",
                "tradingArea": "三里屯、工体|东直门商圈",
                "hotelName": "北京红驿栈精品酒店东直门店",
                "nearAddress": "在鼎信大厦附近",
                "dangci": "2",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "hta1150890a": "6",
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": true,
            "rankInfo": 6144,
            "logicBit": 3760455936,
            "activity": 167837696,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "三里屯、工体|东直门商圈, 在鼎信大厦附近",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": false,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": false,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 2,
            "specialPriceBit": 2496,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 2,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "2147483647",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "156",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "156",
            "isLM": "0",
            "id": "beijing_city_2601",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "147",
                "isCwt": "",
                "CommentScore": "4.4",
                "isTop500": "",
                "gpoint": "39.874638,116.34539",
                "HasInternetAccess": "免费",
                "CommentCount": "222",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201306/02/NNNN2dNiwOKaaSTUN120.jpg",
                "whenFitment": "",
                "hotelAddress": "北京市西城区鸭子桥路39号",
                "theme": "",
                "WhenBuilt": "2008",
                "HotelArea": "西城区",
                "PolicyInfo": "",
                "tradingArea": "菜户营地区",
                "hotelName": "7天酒店北京大观园店",
                "nearAddress": "",
                "dangci": "1",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "hta1243466a": "6",
                "hta1015l00a": "7",
                "hta1243466b": "6",
                "hta0000216b": "6",
                "hta1150890a": "6",
                "hta1242241c": "7",
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": false,
            "rankInfo": 1,
            "logicBit": 3758358788,
            "activity": 134283264,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "菜户营地区",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": true,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": true,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 0,
            "specialPriceBit": 128,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 2,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "2147483647",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "460",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "460",
            "isLM": "0",
            "id": "beijing_city_33684",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "658",
                "isCwt": "",
                "CommentScore": "4.6",
                "isTop500": "",
                "gpoint": "39.97767,116.481445",
                "HasInternetAccess": "免费",
                "CommentCount": "453",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201506/01/JhS1_tJIhekfLvZZJ120.jpg",
                "whenFitment": "2015",
                "hotelAddress": "北京市朝阳区将台路甲2号",
                "theme": "",
                "WhenBuilt": "2015",
                "HotelArea": "",
                "PolicyInfo": "",
                "tradingArea": "酒仙桥、798艺术区|望京商圈",
                "hotelName": "北京燕翔谭阁美饭店",
                "nearAddress": "靠近丽都广场",
                "dangci": "3",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "hta1183809a": "6",
                "hta0992818a": "6",
                "qtav2000101": "6",
                "wiqtaota002": "6",
                "hta0989170a": "6",
                "hta1119445a": "6",
                "hta0993282a": "6",
                "hta0990114a": "6",
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": false,
            "rankInfo": 0,
            "logicBit": 3762553092,
            "activity": 176226304,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "酒仙桥、798艺术区|望京商圈, 靠近丽都广场",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": false,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": true,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 0,
            "specialPriceBit": 128,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 2,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "2147483647",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "362",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "362",
            "isLM": "1",
            "id": "beijing_city_2712",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": true,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "312",
                "isCwt": "",
                "CommentScore": "4.4",
                "isTop500": "",
                "gpoint": "39.9367,116.273735",
                "HasInternetAccess": "免费",
                "CommentCount": "659",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201309/04/18ctKQ8t7n5uzfSM1120.jpg",
                "whenFitment": "2008",
                "hotelAddress": "北京市海淀区西四环北路125号",
                "theme": "",
                "WhenBuilt": "2008",
                "HotelArea": "海淀区",
                "PolicyInfo": "",
                "tradingArea": "四季青商圈",
                "hotelName": "北京美泉宫饭店",
                "nearAddress": "靠近京鼎原商务楼",
                "dangci": "4",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "wiqunarqta2": "6",
                "wapqtalm000": "6",
                "wiqtalm0000": "6",
                "hta0989310a": "6",
                "hta1150890a": "7",
                "wapqunarqta": "14",
                "qtav2000028": "6",
                "hta0987966a": "6"
            },
            "showRetureGold": false,
            "lmLowestPrice": true,
            "hasGroupBuy": false,
            "rankInfo": 8390658,
            "logicBit": 3758358784,
            "activity": 65536,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "四季青商圈, 靠近京鼎原商务楼",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": false,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": false,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 1,
            "specialPriceBit": 384,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 1,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "497",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "227",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "227",
            "isLM": "0",
            "id": "beijing_city_30776",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": true,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "275",
                "isCwt": "",
                "CommentScore": "4.6",
                "isTop500": "",
                "gpoint": "39.891052,116.29693",
                "HasInternetAccess": "免费",
                "CommentCount": "534",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201508/17/66I5P25rlBqZeAVq6120.jpg",
                "whenFitment": "2015",
                "hotelAddress": "北京市海淀区吴家场路53号（金鑫大厦东侧100米路南）",
                "theme": "",
                "WhenBuilt": "2015",
                "HotelArea": "海淀区",
                "PolicyInfo": "",
                "tradingArea": "六里桥地区",
                "hotelName": "北京朗姆酒店",
                "nearAddress": "",
                "dangci": "2",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": true,
            "rankInfo": 4294967297,
            "logicBit": 3760455936,
            "activity": 65536,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "六里桥地区",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": true,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": false,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 2,
            "specialPriceBit": 2496,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 2,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "2147483647",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "907",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "907",
            "isLM": "0",
            "id": "beijing_city_3434",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": true,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "468",
                "isCwt": "",
                "CommentScore": "4.5",
                "isTop500": "",
                "gpoint": "39.997765,116.31338",
                "HasInternetAccess": "免费",
                "CommentCount": "1080",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201212/04/nz078uvcJVsj5w56v120.jpg",
                "whenFitment": "",
                "hotelAddress": "北京市海淀区中关村北大街127号",
                "theme": "",
                "WhenBuilt": "2008",
                "HotelArea": "海淀区",
                "PolicyInfo": "",
                "tradingArea": "中关村商圈|西苑区域",
                "hotelName": "北京北大博雅国际酒店",
                "nearAddress": "靠近中华皮影文化城",
                "dangci": "4",
                "hasWifiInRoom": "0",
                "hotelStars": "5",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "hta0989310a": "6",
                "hta1150890a": "6",
                "wapqunarqta": "30"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": false,
            "rankInfo": 2048,
            "logicBit": 3758358784,
            "activity": 167837696,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "中关村商圈|西苑区域, 靠近中华皮影文化城",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": false,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": false,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 0,
            "specialPriceBit": 1152,
            "hasExclusive": true,
            "hasGift": false,
            "mobileRoomStatus": 2,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "2147483647",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "460",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "460",
            "isLM": "0",
            "id": "beijing_city_11847",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "353",
                "isCwt": "",
                "CommentScore": "4.6",
                "isTop500": "",
                "gpoint": "39.88625,116.35632",
                "HasInternetAccess": "免费",
                "CommentCount": "224",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201303/18/JhS1_tJcgOdMdxodJ120.jpg",
                "whenFitment": "2012",
                "hotelAddress": "北京市西城区（原宣武区）白广路二条甲3号",
                "theme": "",
                "WhenBuilt": "1998",
                "HotelArea": "西城区",
                "PolicyInfo": "",
                "tradingArea": "广安门区域",
                "hotelName": "北京云天酒店",
                "nearAddress": "靠近水利部",
                "dangci": "3",
                "hasWifiInRoom": "2",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "1"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "hta0989310a": "6",
                "hta1150890a": "6",
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": false,
            "rankInfo": 0,
            "logicBit": 262404,
            "activity": 167837696,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "广安门区域, 靠近水利部",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": false,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": true,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 0,
            "specialPriceBit": 128,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 2,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "2147483647",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "474",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "474",
            "isLM": "1",
            "id": "beijing_city_4143",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "352",
                "isCwt": "",
                "CommentScore": "4.4",
                "isTop500": "",
                "gpoint": "39.888897,116.653244",
                "HasInternetAccess": "免费",
                "CommentCount": "748",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201307/08/NNNN2dccniVlbU5uN120.jpg",
                "whenFitment": "2013",
                "hotelAddress": "北京市通州区九棵树西路201号",
                "theme": "",
                "WhenBuilt": "2009",
                "HotelArea": "通州区",
                "PolicyInfo": "",
                "tradingArea": "梨园区域",
                "hotelName": "北京太阳花酒店",
                "nearAddress": "在九棵树地铁站B口附近",
                "dangci": "3",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "wapqtalm000": "14",
                "hta0987571a": "6",
                "hta0989310a": "6",
                "hta1150890a": "7",
                "wapqunarqta": "14",
                "wiqunarqta5": "6"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": false,
            "rankInfo": 4294971409,
            "logicBit": 3762553088,
            "activity": 167837696,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "梨园区域, 在九棵树地铁站B口附近",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": true,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": false,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 1,
            "specialPriceBit": 1408,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 1,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "528",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "607",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "607",
            "isLM": "1",
            "id": "beijing_city_2232",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": true,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "Y",
                "MiniRetailPrice": "418",
                "isCwt": "",
                "CommentScore": "4.5",
                "isTop500": "",
                "gpoint": "39.95031,116.39785",
                "HasInternetAccess": "免费",
                "CommentCount": "1231",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201212/03/nz078uvchMyV33zVv120.jpg",
                "whenFitment": "2008",
                "hotelAddress": "北京市东城区安外西滨河路26号",
                "theme": "",
                "WhenBuilt": "2006",
                "HotelArea": "东城区",
                "PolicyInfo": "",
                "tradingArea": "后海、什刹海|安贞区域",
                "hotelName": "北京汉华国际饭店",
                "nearAddress": "靠近鼓楼大街地铁站B口",
                "dangci": "4",
                "hasWifiInRoom": "0",
                "hotelStars": "5",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "wapqtalm000": "6",
                "hta0989310a": "6",
                "hta1150890a": "6",
                "wapqunarqta": "14",
                "wiqunarqta5": "6"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": false,
            "rankInfo": 2049,
            "logicBit": 3758358784,
            "activity": 167837696,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "后海、什刹海|安贞区域, 靠近鼓楼大街地铁站B口",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": true,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": false,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 1,
            "specialPriceBit": 1408,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 1,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "665",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }, {
            "hourRoomRecLm": false,
            "discount": "10.0",
            "recommendDesc": "",
            "hActivityLabels": [{
                "listPriority": -2,
                "wapInfoIndex": -1,
                "activityIndex": -1,
                "listNotShow": false,
                "labelType": 1,
                "detailId": 68,
                "type": 1,
                "logicBitIndex": 18,
                "detailMutexIds": [],
                "listId": 68,
                "activityId": "",
                "promotionIndex": -1,
                "bgColor": -43691,
                "specialPriceBitIndex": -1,
                "listMutexIds": [],
                "botaoPromotionWrappers": [],
                "tmpColor": -1,
                "lmPromotionWrappers": [],
                "promotionWrappers": [],
                "listSort": -2,
                "hourResultInfoIndex": -1,
                "label": "会员红包",
                "wrapperIds": [],
                "detailSort": 2,
                "wapTypeIndex": 0,
                "rankInfoIndex": -1,
                "detailNotShow": false,
                "fontColor": -1,
                "desc": ""
            }],
            "hasTeHui": false,
            "specialRec": 0,
            "price": "248",
            "qualityLabelList": [],
            "topList": 0,
            "mobilePrice": "248",
            "isLM": "1",
            "id": "beijing_city_29092",
            "hasDistancePreference": false,
            "hasChainPrice": false,
            "wapType": 0,
            "selected": {
                "poi": {},
                "fts2": {}
            },
            "hasSignInRed": false,
            "hasBNB9Hongbao": false,
            "showRedPack": false,
            "corrDist": "",
            "hotelLabel": [],
            "hasFiveDiscount": false,
            "hasFiveStarDacu": false,
            "timeLimitPrice": "",
            "supportHongBao": true,
            "attrs": {
                "isWebFree": "N",
                "MiniRetailPrice": "-1",
                "isCwt": "",
                "CommentScore": "4.4",
                "isTop500": "",
                "gpoint": "39.978363,116.42421",
                "HasInternetAccess": "无",
                "CommentCount": "370",
                "WifiAccess": "Y",
                "imageID": "http://userimg.qunar.com/imgs/201506/23/HJI_JOQ3TfyoM7LMD120.jpg",
                "whenFitment": "2014",
                "hotelAddress": "北京朝阳区惠新东街19号（近对外经济贸易大学、地铁5号线10号线惠新西街南口站）",
                "theme": "",
                "WhenBuilt": "2014",
                "HotelArea": "朝阳区",
                "PolicyInfo": "",
                "tradingArea": "芍药居区域",
                "hotelName": "北京影驿站主题酒店（惠桥店）",
                "nearAddress": "靠近对外经贸大学南",
                "dangci": "5",
                "hasWifiInRoom": "0",
                "hotelStars": "0",
                "isLp": "",
                "hasParkingArea2": "0"
            },
            "hasDay7Crash": false,
            "promotionFlags": {
                "wapqtalm000": "14",
                "hta0989310a": "6",
                "hta1150890a": "6",
                "wapqunarqta": "14"
            },
            "showRetureGold": false,
            "lmLowestPrice": false,
            "hasGroupBuy": true,
            "rankInfo": 268452864,
            "logicBit": 3760455940,
            "activity": 65536,
            "distance": "0",
            "hourResultInfo": 0,
            "jpM": 0,
            "avgPrice": "2147483647",
            "browseMonth": 0,
            "showAddr": "芍药居区域, 靠近对外经贸大学南",
            "ppcImgUrl": "",
            "hasBNBHongbao": false,
            "hasQuick": false,
            "cityName": "北京",
            "hasDay7": false,
            "packOperateType": 0,
            "lmFullRoom": false,
            "showCanUserGold": true,
            "services": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "tagName": "",
            "wapInfo": 3,
            "specialPriceBit": 2496,
            "hasExclusive": false,
            "hasGift": false,
            "mobileRoomStatus": 1,
            "hasFiveStarHongbao": false,
            "servicePics": [{
                "name": "wifi",
                "tag": "WIFI_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/WIFI_LIST_30.png"
            }, {
                "name": "停车场",
                "tag": "PARKING_LIST",
                "url": "http://source.qunar.com/site/images/wap/servicesv1/PARKING_LIST_30.png"
            }],
            "lmPrice": "268",
            "activityIds": [],
            "bundlingRate": 0,
            "lmOldPrice": "",
            "isLMFullRoom": false
        }],
        "hotkey": [{
            "jumpType": 0,
            "pvCount": 1799,
            "displayName": "天安门",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 1204,
            "displayName": "南锣鼓巷",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 1192,
            "displayName": "北京西站",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 1068,
            "displayName": "北京站",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 986,
            "displayName": "北京南站",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 675,
            "displayName": "首都机场",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 319,
            "displayName": "三里屯",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 293,
            "displayName": "国贸",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 258,
            "displayName": "王府井",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 253,
            "displayName": "东直门",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 228,
            "displayName": "北京大学",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 228,
            "displayName": "西单",
            "tagName": "热门地点"
        }, {
            "jumpType": 0,
            "pvCount": 924,
            "displayName": "锦江之星",
            "tagName": "热门品牌"
        }, {
            "jumpType": 0,
            "pvCount": 836,
            "displayName": "汉庭酒店",
            "tagName": "热门品牌"
        }, {
            "jumpType": 0,
            "pvCount": 808,
            "displayName": "桔子酒店",
            "tagName": "热门品牌"
        }, {
            "jumpType": 0,
            "pvCount": 505,
            "displayName": "速8",
            "tagName": "热门品牌"
        }, {
            "jumpType": 0,
            "pvCount": 342,
            "displayName": "格林豪泰",
            "tagName": "热门品牌"
        }, {
            "jumpType": 0,
            "pvCount": 254,
            "displayName": "智选假日",
            "tagName": "热门品牌"
        }, {
            "jumpType": 1,
            "pvCount": 0,
            "displayName": "更多地点...",
            "tagName": "热门地点"
        }, {
            "jumpType": 1,
            "pvCount": 0,
            "displayName": "更多品牌...",
            "tagName": "热门品牌"
        }],
        "areas": [
            "东直门商圈",
            "首都机场",
            "王府井商圈",
            "五道口、学院路",
            "三里屯、工体",
            "安贞区域",
            "后海、什刹海",
            "西直门商圈",
            "中关村商圈",
            "六里桥地区",
            "朝阳门区域",
            "前门商圈",
            "广安门区域",
            "北太平庄区域",
            "崇文门商圈",
            "天桥区域",
            "国贸地区",
            "潘家园地区",
            "望京商圈",
            "奥体中心区域",
            "马家堡地区",
            "万柳商圈",
            "劲松地区",
            "酒仙桥、798艺术区",
            "青年路商圈",
            "亮马桥区域",
            "五棵松商圈",
            "建国门区域",
            "西三旗区域",
            "清河区域",
            "十里河商圈",
            "朝外商圈",
            "北下关区域",
            "大红门地区",
            "展览路区域",
            "青塔区域",
            "枣园",
            "魏公村商圈",
            "四季青商圈",
            "西单商圈",
            "国展区域",
            "管庄地区",
            "亦庄地区",
            "亚运村商圈",
            "大望路区域",
            "梨园区域",
            "草桥地区",
            "宣武门区域",
            "方庄商圈",
            "公主坟商圈",
            "回龙观区域",
            "广渠门地区",
            "木樨地区域",
            "石佛营区域",
            "天通苑",
            "西四区域",
            "上地商圈",
            "欢乐谷",
            "丰台科技园商圈",
            "苹果园区域",
            "南苑地区",
            "南礼士路区域",
            "北大地区域",
            "北苑区域",
            "四惠区域",
            "田村地区",
            "沙子口地区",
            "团结湖区域",
            "玉泉营地区",
            "定福庄地区",
            "良乡区域",
            "古城区域",
            "十八里店地区",
            "顺义温泉休闲区",
            "牛街区域",
            "西苑区域",
            "甘家口区域",
            "菜市口地区",
            "芍药居区域",
            "太阳宫区域",
            "木樨园地区",
            "新华大街地区",
            "高碑店地区",
            "沙河",
            "八角区域",
            "鲁谷区域",
            "甜水园",
            "红庙区域",
            "百子湾地区",
            "左安门地区",
            "车道沟区域",
            "旧宫地区",
            "东关区域",
            "西便门区域",
            "莽山森林公园",
            "雁栖湖",
            "八大处区域",
            "大峪区域",
            "东坝商圈",
            "香山",
            "北京植物园",
            "张家湾",
            "模式口区域",
            "房山城关",
            "八达岭长城",
            "窦店",
            "凤凰岭",
            "明十三陵",
            "红螺寺",
            "慕田峪长城",
            "密云水库",
            "黑龙潭",
            "云蒙山",
            "双龙峡",
            "大觉寺"
        ],
        "pics": [{
            "src": "http://source.qunar.com/site/images/wap/home/recommend/small/1130_gg_luhu2.jpg",
            "url": "http://qde.qunar.com/event.ng/Type=click&FlightID=187242&AdID=244845&TargetID=356&Segments=253,13&Targets=356&Values=245,264,301,5480,204&RawValues=&Redirect=BlfGE8P3HY4P1Xc3XGZj6l75s57x8ebBfcDhCmiRYEw="
        }, {
            "src": "http://source.qunar.com/site/images/wap/home/recommend/small/1130_gg_gbhg.jpg",
            "url": "http://qde.qunar.com/event.ng/Type=click&FlightID=187551&AdID=245016&TargetID=356&Segments=253,13&Targets=356&Values=245,264,301,5480,204&RawValues=&Redirect=saWVDBJDE8GndP4IKWAAlWtbnN68smVf2K6ikDPX4ds="
        }, {
            "src": "http://source.qunar.com/site/images/wap/home/recommend/small/hongbao0806.jpg",
            "url": "https://pay.qunar.com/mobile/member/activity/index.htm?amount=&busiTypeId=ZFZX&did=000000&gid=8438932D-5548-D769-1AF7-22274CDE88E4&merchantCode=ZFZXBKFHBJK&option=0&pid=10010&schema=&source=pay_appbanner&userId=&version=20140808&vid=000000&HMAC=9db3625962bbdf521d245200e625b182"
        }, {
            "src": "http://source.qunar.com/site/images/wap/home/recommend/small/1124_jd_wqdpd.jpg",
            "url": "http://touch.qunar.com/h5/activity/ElevenHotelRed?activityNum=2&bd_source=huodong20&fromForLog=7001"
        }, {
            "src": "http://source.qunar.com/site/images/wap/home/recommend/small/1130_jd_jdms.jpg",
            "url": "http://tuan.qunar.com/ext/sact/IjAjim?&bd_source=tg_hd_00015"
        }, {
            "src": "http://source.qunar.com/site/images/wap/home/recommend/small/1111_jd_1yzzdf.jpg",
            "url": "http://m.qunar.com/zhuanti/20151127zhongdianfangmiaosha_optimize_normal.html?bd_source=zhongdianfangl_hotel"
        }, {
            "src": "http://source.qunar.com/site/images/wap/home/recommend/small/1130_gjc_hwydlb.jpg",
            "url": "http://intercar.qunar.com/touch/appReversion/voucherPage?from=803"
        }]
    }
}
