module.exports = {
    "ret": true,
    "errcode": 0,
    "msg": "",
    "data": {
        "cheaperBrands": [{
            "groupType": "经济型",
            "qname": "锦江之星",
            "dname": "锦江之星",
            "group": "cheap",
            "hotDegree": 209
        }, {
            "groupType": "经济型",
            "qname": "汉庭酒店",
            "dname": "汉庭酒店",
            "group": "cheap",
            "hotDegree": 204
        }, {
            "groupType": "经济型",
            "qname": "如家",
            "dname": "如家",
            "group": "cheap",
            "hotDegree": 193
        }, {
            "groupType": "经济型",
            "qname": "格林豪泰",
            "dname": "格林豪泰",
            "group": "cheap",
            "hotDegree": 125
        }, {
            "groupType": "经济型",
            "qname": "速8",
            "dname": "速8",
            "group": "cheap",
            "hotDegree": 104
        }, {
            "groupType": "经济型",
            "qname": "桔子酒店",
            "dname": "桔子酒店",
            "group": "cheap",
            "hotDegree": 84
        }],
        "airMixTrain": [{
            "qname": "北京站",
            "dname": "北京站",
            "hotDegree": 153
        }, {
            "qname": "北京西站",
            "dname": "北京西站",
            "hotDegree": 136
        }, {
            "qname": "北京南站",
            "dname": "北京南站",
            "hotDegree": 82
        }, {
            "qname": "首都机场T2航站楼",
            "dname": "首都机场T2航站楼",
            "hotDegree": 26
        }, {
            "qname": "首都机场T3航站楼",
            "dname": "首都机场T3航站楼",
            "hotDegree": 20
        }, {
            "qname": "北京北站",
            "dname": "北京北站",
            "hotDegree": 17
        }],
        "higherBrands": [{
            "groupType": "豪华",
            "qname": "希尔顿",
            "dname": "希尔顿",
            "group": "higher",
            "hotDegree": 55
        }, {
            "groupType": "高级",
            "qname": "桔子水晶",
            "dname": "桔子水晶",
            "group": "normal",
            "hotDegree": 32
        }, {
            "groupType": "高级",
            "qname": "假日",
            "dname": "假日",
            "group": "normal",
            "hotDegree": 29
        }, {
            "groupType": "豪华",
            "qname": "喜来登",
            "dname": "喜来登",
            "group": "higher",
            "hotDegree": 28
        }, {
            "groupType": "豪华",
            "qname": "万豪",
            "dname": "万豪",
            "group": "higher",
            "hotDegree": 27
        }, {
            "groupType": "豪华",
            "qname": "香格里拉",
            "dname": "香格里拉",
            "group": "higher",
            "hotDegree": 21
        }],
        "newTradeArea": [{
            "hotelCount": 390,
            "desc": "东直门商圈东直门商圈东直门商圈东直门商圈东直门商圈东直门商圈",
            "qname": "东直门商圈",
            "dname": "东直门商圈",
            "hotDegree": 19
        }, {
            "hotelCount": 287,
            "desc": "位于北京西城区西直门商圈",
            "qname": "西直门商圈",
            "dname": "西直门商圈",
            "hotDegree": 8
        }]
    }
};
