var todayDate = new Date(),
	todayArr = [todayDate.getFullYear(), todayDate.getMonth() + 1, todayDate.getDate()],
	todayStr = todayArr.join('-').replace(/[^-]+/g, function(val) {
		return ~~val > 9 ? val : '0' + val;
	}),
	todayWeek = todayDate.getDay(),

	tomorrowDate = new Date(todayDate.getTime() + 1 * 24 * 60 * 60 * 1000),
	tomorrowArr = [tomorrowDate.getFullYear(), tomorrowDate.getMonth() + 1, tomorrowDate.getDate()],
	tomorrowStr = tomorrowArr.join('-').replace(/[^-]+/g, function(val) {
		return ~~val > 9 ? val : '0' + val;
	}),
	tomorrowWeek = tomorrowDate.getDay();
console.log(todayStr)
var commonParam = {
	"isLogin": false,
	"host": {"touch": "http://tcdev.dev.qunar.com", "userCenter": "http://user.qunar.com"},
	"userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1",
	"tomorrowDate": ["2016", "06", "18", "6"],
	"currentDateStr": "2016-06-17",
	"skin": {
		"orderLogin": true,
		"callApp": true,
		"full_download": true,
		"appBanner": true,
		"roomtype_tip": true,
		"back": true,
		"ad": false,
		"nearby": true,
		"header": true,
		"appLayer": true,
		"searchHeaderImg": true
	},
	"url": "http://touch.qunar.com/hotel/hotelorderinfo.c?tag=hotel_b6ffbeb0f5f75778d6b3b8bc753b7bb3_17&roomId=3333860987_783676&wrapperId=hta9008oh6k&planId=MOBILE_MS_hta9008oh6k&seq=tokyo_4657&logicBit=0&mobilePriceType=1&index=0&isLM=0&type=0&city=&keywords=&checkInDate=2016-06-17&checkOutDate=2016-06-18&payType=0&orderType=12&extra=",
	"cookieBdSource": "weixin_touch",
	"v": "",
	"username": "",
	"bdSource": "weixin_touch",
	"t": "",
	"currentDate": ["2016", "06", "17", "5"],
	"q": "",
	"userId": "",
	"tomorrowDateStr": "2016-06-18",
	"referer": "",
	"ads": {
		"hotel_index_top_ad": "//qde.qunar.com/js.ng/chan=hotel&pg=home&plateform=wap&pos=top&site=wap.qunar&size=320x44&adtest=prod&terminal=touch",
		"hotel_list_top_ad": "//qde.qunar.com/js.ng/chan=hotel&pg=list&plateform=wap&pos=top&site=wap.qunar&size=320x44&adtest=prod&terminal=touch",
		"hotel_detail_bottom_ad": "//qde.qunar.com/js.ng/chan=hotel&pg=detail&plateform=wap&pos=mid&site=wap.qunar&size=320x44&adtest=prod&terminal=touch",
		"hotel_detail_top_ad": "//qde.qunar.com/js.ng/chan=hotel&pg=detail&plateform=wap&pos=top&site=wap.qunar&size=320x44&adtest=prod&terminal=touch",
		"hotel_list_bottom_ad": "//qde.qunar.com/js.ng/chan=hotel&pg=list&plateform=wap&pos=mid&site=wap.qunar&size=320x44&adtest=prod&terminal=touch",
		"index_index_bottom_ad": "//qde.qunar.com/js.ng/chan=homepage&pg=home&plateform=wap&pos=mid&site=wap.qunar&size=320x44&adtest=prod&terminal=touch",
		"hotel_index_bottom_ad": "//qde.qunar.com/js.ng/chan=hotel&pg=home&plateform=wap&pos=mid&site=wap.qunar&size=320x44&adtest=prod&terminal=touch",
		"index_index_top_ad": "//qde.qunar.com/js.ng/chan=homepage&pg=home&plateform=wap&pos=top&site=wap.qunar&size=320x44&adtest=prod&terminal=touch"
	}
};
var data = {
	isend: false,
	needLink: true,
	"sign": "7384AE44FA876A0B7EE797A3C2E398BC",
	"order": {
		"uid": "tc_df6bd68124647481_154e07b4201_d33f",
		"ifAdditionalPay": false,
		"extendStayInfo": {"maxDays": 0, "orderType": 12, "canExtendStay": false},
		"ifOcncPay": false,
		"cashBackStatus": 0,
		"promotionDetails": [{
			"promotionCode": "SUBTRACT",
			"promotionData": {
				"totalCount": 0,
				"avgValue": {"amount": 3.0, "currency": "CNY"},
				"entityType": "MONEY",
				"totalValue": {"amount": 3.0, "currency": "CNY"},
				"renderSignal": 0
			},
			"promotionName": "直减",
			"promotionGroup": "SUBTRACT"
		}],
		"payTimeDuration": "0",
		"hasPayAmount": 0,
		"ifCheckInOrder": false,
		"canUseCamelCard": true,
		"ifFlashCredit": false,
		"productType": 5,
		"orderInfo": {
			"referTotalPrice": "",
			"roomId": "",
			"unitPrice": "",
			"preferRule": "",
			"supportCompensate": false,
			"isRemoveArriveTimeTitle": false,
			"warmTips": "请在最晚到店时间之前到达，否则酒店可能无法为您保留房间。",
			"bookNum": 1,
			"maxPersonsPreRoom": 0,
			"passbook": false,
			"contactEmailObj": {"value": "", "prenum": "", "display": ""},
			"cashTips": [],
			"linked": true,
			"commentable": false,
			"activityDesc": "",
			"totalPrice": "224",
			"orderStautsColor": 1,
			"currencySign": "￥",
			"arrearsPrice": "",
			"contactPhone": "15010451867",
			"onlineType": 0,
			"orderDate": "2016-06-17 15:48",
			"cancellation": "订单确认后无法操作变更，预订人非因法定原因取消，将扣收全额预付款作为违约金。（“法定原因”以《合同法》和《消费者权益保护法》规定为准，一般包括自然灾害、政府征用、酒店方过错等导致预订人不能正常入住的情形。）",
			"totalPrize": "",
			"ptTypeDesc": "已减￥3.0",
			"contactPhoneObj": {"value": "15010451867", "prenum": "", "display": "150****1867"},
			"realOrderDate": "2016-06-17 15:48:28",
			"planId": "",
			"payTypeCode": 0,
			"orderStatus": "预订取消",
			"checkIn": "2016-06-17",
			"orderWarmTips": "订单已取消。如需预订其他酒店，请您重新搜索预订。",
			"guestNames": ["xue"],
			"staytime": "06月17日—06月18日 共1晚*1间",
			"checkOut": "2016-06-18",
			"orderNo": "100840718600",
			"orderStatusCode": 5,
			"arriveTime": "17:00",
			"updateTimeTips": "最新订单状态已于2016-07-21 12:54更新",
			"contactName": "xue",
			"payType": "在线支付",
			"roomPrice": "",
			"fromWeekTime": "星期五",
			"smobile": "14a2fc48c7cc58a08b1616e6238c3454cc931025a2f16f22706e66886b57236d",
			"totalMoney": ""
		},
		"paySource": 0,
		"catom": 0,
		"discountInfo": {
			"detailFees": [{
				"detailFees": [{"text": "房费", "price": "￥227.0"}, {
					"text": "直减",
					"price": "-￥3"
				}], "text": "在线付款", "price": "￥224"
			}],
			"stayInfo": "1间*1晚",
			"discounts": [{"desc": "需在线支付", "price": "￥224", "name": "订单总额", "type": 1}, {
				"price": "￥3",
				"name": "直减",
				"type": 2,
				"discountCode": "SUBTRACT"
			}]
		},
		"qtaOrderStatusCode": 3,
		"ifEReceiptLetter": false,
		"parentProductType": 0,
		"starTicketBack": 0.0,
		"modifyInfo": {"modifiable": false, "modifyTooMuch": false},
		"ifStarTicketBack": false,
		"ifCancel": false,
		"baseStatus": 0,
		"userLevel": 0,
		"userName": "kzbvdvy7468",
		"isLoginExpired": false,
		"isQta": true,
		"vid": "91010000",
		"confirmType": "instantConfirm",
		"ifCashBack": false,
		"ifRefund": false,
		"status": 0,
		"orderType": 3,
		"ifApplyCashBack": false,
		"extra": {"ptTypeDesc": "已减￥3.0", "showVouch": false},
		"flagBit": 0,
		"cashierType": "NONE",
		"skipBindCardCashBack": 0,
		"hotelInfo": {
			"roomArea": "",
			"foreignHotel": false,
			"starDc": "",
			"breakfast": "无早",
			"cityName": "北京",
			"score": "",
			"roomId": "10262108_468467",
			"touchMapUrl": "",
			"hotelId": "2487602",
			"wifi": "免费wifi",
			"hotelAddress": "北京朝阳区安定门外立水桥北8号",
			"floor": "",
			"hotelName": "莫泰连锁酒店北京立水桥地铁站店",
			"imageID": "http://himg1.qunarzz.com/imgs/201512/21/66I5P25b8BfupQrl676.jpg",
			"webfree": "无宽带",
			"roomName": "特惠双人房-不含早（预付）-去哪儿网力荐商家",
			"hotelPhone": "-010-84846677",
			"useNativeIMap": true,
			"gpoint": "40.055004,116.412544",
			"bedType": "双床",
			"roomTypeName": "特惠双人房",
			"hotelSeq": "beijing_city_25134"
		},
		"repayType": 0,
		"lifeCycle": 4,
		"msg": "成功",
		"mergePayOrder": false,
		"onlineServiceStatus": 1,
		"urgentOrder": false,
		"flag": true,
		"starTicketProductType": 0,
		"activityDetail": {"reduceParttakeFlag": 3},
		"switchBit": 0,
		"tyingInfos": [],
		"ifProlong": false,
		"canApplyNoShow": false,
		"qtaUserStatusCode": 10,
		"saleUnit": 0,
		"hotCity": false,
		"carPromotionVersion": 0,
		"hasEnoughPromo": true,
		"realCashBack": "0",
		"needBindBankCard": false,
		"checkInCashBack": 0.0,
		"guara": false,
		"shareOrder": false,
		"userMemberStatus": -1,
		"detailPriceInfo": "{\"hotelOrderCount\":0,\"hotelOrderMonthCount\":0,\"servicePics\":[{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/ROOM_WIFI_big_v1.png\",\"tag\":\"ROOM_WIFI\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/ROOM_WIFI_720.png\",\"name\":\"房间WiFi\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/NETWORK_big_v1.png\",\"tag\":\"FREE_NETWORK\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/NETWORK_720.png\",\"name\":\"免费上网\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/PUBLIC_WIFI_big_v1.png\",\"tag\":\"PUBLIC_WIFI\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/PUBLIC_WIFI_720.png\",\"name\":\"大堂WiFi\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/PARKING_big_v1.png\",\"tag\":\"FREE_PARKING\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/PARKING_720.png\",\"name\":\"免费停车\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/WAKEUP_big_v1.png\",\"tag\":\"WAKEUP\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/WAKEUP_720.png\",\"name\":\"叫醒服务\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/HAIRDRYER_big_v1.png\",\"tag\":\"HAIRDRYER\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/HAIRDRYER_720.png\",\"name\":\"吹风机\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/HOTWATER_H24_big_v1.png\",\"tag\":\"HOTWATER_H24\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/HOTWATER_H24_720.png\",\"name\":\"全天热水\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/PICKUP_big_v1.png\",\"tag\":\"PICKUP\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/PICKUP_720.png\",\"name\":\"接机服务\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/CHINESE_RESTAURANT_big_v1.png\",\"tag\":\"CHINESE_RESTAURANT\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/CHINESE_RESTAURANT_720.png\",\"name\":\"中式餐厅\"},{\"bigUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/NONSMOKING_ROOM_big_v1.png\",\"tag\":\"NONSMOKING_ROOM\",\"url\":\"http://source.qunar.com/site/images/wap/servicesv1/NONSMOKING_ROOM_720.png\",\"name\":\"无烟房\"}],\"fromDate\":\"2016-07-21\",\"toDate\":\"2016-07-22\",\"lastMin\":false,\"price\":\"\",\"sortType\":1,\"rooms\":[],\"bizSwitch\":{\"nonNakedPriceOpen\":false,\"needSplitGuoJiTax\":false,\"userCoinOpen\":false,\"bindCardBackOpen\":false},\"logicResult\":{\"userTypeBit\":0},\"dinfo\":{\"imgurl\":\"http://himg1.qunarzz.com/imgs/201512/21/66I5P25b8BfupQrl676.jpg\",\"hotelStars\":\"\",\"dangci\":\"1\",\"whenFitment\":\"2014\",\"hotelBrand\":\"motai\",\"commentCount\":\"298\",\"city\":\"北京\",\"hotelSeq\":\"beijing_city_25134\",\"score\":\"4.6\",\"useNativeIMap\":true,\"phone\":\"010-84846677\",\"area\":\"北苑区域|天通苑\",\"oneSentence\":\"位于北京市朝阳区安定门外立水桥北8号（华泰汽车旁边或5/13号线立水桥地铁站A口出）\",\"gpoint\":\"40.055004,116.412544\",\"webfree\":\"Y\",\"desc\":\"莫泰连锁酒店北京立水桥地铁站店地处北京最大的社区天通苑社区，周边繁华、交通便利。地铁5号、13号线立水桥站出A口即到；距中国国际展览中心（新馆）地铁仅8站；家乐福、万达影城、明珠百货、祥和赏玩世界是您购物娱乐的最佳场所，步行10分钟即到。免费的40个停车位给您带来方便、快捷；酒店装修色彩柔和舒适；房间宽敞、明亮，在您免费享受无线上网的同时也能感受到繁华都市中的一点儿宁静。让我们专业、周到的服务来换取您舒适的体验吧！\",\"imageCount\":\"32\",\"currencySign\":\"¥\",\"dangciText\":\"经济型\",\"btime\":\"2014\",\"rnum\":\"125\",\"whenOpen\":\"2014\",\"foreignHotel\":false,\"highStartHotel\":false,\"add\":\"北京朝阳区安定门外立水桥北8号\",\"facilities\":[{\"datas\":[{\"shortName\":\"房间wifi\",\"sort\":2147483647,\"item\":\"房间wifi\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":1,\"lowStarSort\":1,\"overseasSort\":3,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/hasWifiInRoom.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/hasWifiInRoom_big.png\",\"field\":\"hasWifiInRoom\",\"type\":\"网络设施\",\"icon\":0},{\"shortName\":\"公共wifi\",\"sort\":2147483647,\"item\":\"公共区域wifi\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":1,\"lowStarSort\":1,\"overseasSort\":3,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/WifiAccess.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/WifiAccess_big.png\",\"field\":\"WifiAccess\",\"type\":\"网络设施\",\"icon\":0},{\"shortName\":\"宽带上网\",\"sort\":2147483647,\"item\":\"宽带上网\",\"desc\":\"(免费)\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":1,\"lowStarSort\":1,\"overseasSort\":3,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/isWebFree.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/isWebFree_big.png\",\"field\":\"HasInternetAccess\",\"type\":\"网络设施\",\"icon\":0}],\"type\":\"网络设施\"},{\"datas\":[{\"shortName\":\"全天热水\",\"sort\":2147483647,\"item\":\"全天热水\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":29,\"lowStarSort\":2,\"overseasSort\":29,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/has24hotwater.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/has24hotwater_big.png\",\"field\":\"has24hotwater\",\"type\":\"房间设施\",\"icon\":0},{\"shortName\":\"吹风机\",\"sort\":2147483647,\"item\":\"吹风机\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":30,\"lowStarSort\":4,\"overseasSort\":30,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/HasHairDryer.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/HasHairDryer_big.png\",\"field\":\"HasHairDryer\",\"type\":\"房间设施\",\"icon\":0}],\"type\":\"房间设施\"},{\"datas\":[{\"shortName\":\"中式餐厅\",\"sort\":2147483647,\"item\":\"中式餐厅\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":10,\"lowStarSort\":8,\"overseasSort\":10,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/hasChineseRestaurant.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/hasChineseRestaurant_big.png\",\"field\":\"hasChineseRestaurant\",\"type\":\"通用设施\",\"icon\":0},{\"shortName\":\"无烟房\",\"sort\":2147483647,\"item\":\"无烟房\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":17,\"lowStarSort\":14,\"overseasSort\":17,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/HasNonSmokingAvailable.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/HasNonSmokingAvailable_big.png\",\"field\":\"HasNonSmokingAvailable\",\"type\":\"通用设施\",\"icon\":0},{\"shortName\":\"停车场\",\"sort\":2147483647,\"item\":\"免费停车\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":20,\"lowStarSort\":6,\"overseasSort\":20,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/hasParkingArea2.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/hasParkingArea2_big.png\",\"field\":\"hasParkingArea2\",\"type\":\"通用设施\",\"icon\":0},{\"shortName\":\"早餐\",\"sort\":2147483647,\"item\":\"早餐\",\"color\":-14964294,\"oldVersionFilter\":false,\"highStarSort\":41,\"lowStarSort\":20,\"overseasSort\":41,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/hasBreakfast.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/hasBreakfast_big.png\",\"field\":\"hasBreakfast\",\"type\":\"通用设施\",\"icon\":0}],\"type\":\"通用设施\"},{\"datas\":[{\"shortName\":\"接机服务\",\"sort\":2147483647,\"item\":\"接机服务\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":3,\"lowStarSort\":16,\"overseasSort\":5,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/HasAirportPickUp.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/HasAirportPickUp_big.png\",\"field\":\"HasAirportPickUp\",\"type\":\"服务项目\",\"icon\":0},{\"shortName\":\"洗衣服务\",\"sort\":2147483647,\"item\":\"洗衣服务\",\"color\":-14964294,\"oldVersionFilter\":false,\"highStarSort\":21,\"lowStarSort\":18,\"overseasSort\":21,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/HasGuestLaundromat.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/HasGuestLaundromat_big.png\",\"field\":\"HasGuestLaundromat\",\"type\":\"服务项目\",\"icon\":0},{\"shortName\":\"唤醒服务\",\"sort\":2147483647,\"item\":\"唤醒服务\",\"color\":-14964294,\"oldVersionFilter\":true,\"highStarSort\":28,\"lowStarSort\":12,\"overseasSort\":28,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/HasWakeUpService.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/HasWakeUpService_big.png\",\"field\":\"HasWakeUpService\",\"type\":\"服务项目\",\"icon\":0},{\"shortName\":\"行李寄存\",\"sort\":2147483647,\"item\":\"行李寄存\",\"color\":-14964294,\"oldVersionFilter\":false,\"highStarSort\":31,\"lowStarSort\":5,\"overseasSort\":31,\"iconUrl\":\"http://source.qunar.com/site/images/wap/servicesv1/hasLeftLuggage.png\",\"display\":true,\"iconBig\":\"http://source.qunar.com/site/images/wap/servicesv1/hasLeftLuggage_big.png\",\"field\":\"hasLeftLuggage\",\"type\":\"服务项目\",\"icon\":0}],\"type\":\"服务项目\"}],\"name\":\"莫泰连锁酒店北京立水桥地铁站店\",\"static\":false,\"service\":\"\"},\"collect\":false,\"singleDayCalendar\":false,\"orderAll\":false,\"displayPriceNum\":10,\"servicePicCount\":8,\"rtDisclaimerNote\":\"\",\"hasGroupPrice\":false,\"mapLineSwitchOn\":false,\"domesticMapRender\":true,\"quickFilters\":[],\"priceFilterList\":[],\"showRedPack\":false,\"wantReside\":false,\"cityRelation\":0,\"timeZone\":{\"utc\":\"GMT+8:00\",\"foreignCity\":false}}",
		"servicePhones": [{
			"subTitle": "拨打去哪儿网客服电话",
			"title": "其他帮助",
			"menu": "拨打去哪儿网客服电话",
			"telephone": "10101234"
		}],
		"onlineServiceUrl": "http://complain.order.qunar.com/complain/complain.html?businessType=hotel&source=complain.app&orderNo=100840718600",
		"hasMatchHourRoomPrice": false,
		"bindCardType": 0,
		"ifCanShare": false,
		"deductSource": "",
		"ifConfirmationLetter": false,
		"mockTaxation": false,
		"prefers": [],
		"cancelRule": {
			"cancelType": "NO_CANCEL",
			"cancelRule": "订单确认后无法操作变更，预订人非因法定原因取消，将扣收全额预付款作为违约金。（“法定原因”以《合同法》和《消费者权益保护法》规定为准，一般包括自然灾害、政府征用、酒店方过错等导致预订人不能正常入住的情形。）",
			"cancelName": "订单确认后，不可取消"
		},
		"applyCashBackTips": "",
		"importRules": [],
		"checkInStatus": 0,
		"interHotel": false,
		"pcProductDetail": "{\"busiOrderDetailURL\":\"\",\"busiOrderDetailExURL\":\"&isExtInfo=1\",\"onlyNoticeBatch\":true,\"headData\":[{\"num\":1,\"name\":\"房型\",\"value\":\"特惠双人房\"},{\"num\":2,\"name\":\"床型\",\"value\":\"双床\"},{\"num\":3,\"name\":\"房间数\",\"value\":\"1间\"},{\"num\":4,\"name\":\"入住日期\",\"value\":\"2016-06-17\"},{\"num\":5,\"name\":\"离店日期\",\"value\":\"2016-06-18\"}],\"plainData\":[{\"num\":1,\"name\":\"订单号\",\"value\":100840718600},{\"num\":2,\"name\":\"联系人\",\"value\":\"xue\"},{\"num\":3,\"type\":\"Mobile\",\"name\":\"手机号码\",\"value\":\"150o2l51867\"},{\"num\":4,\"name\":\"入住人\",\"value\":[\"xue\"]},{\"num\":5,\"name\":\"宽带\",\"value\":\"无\"},{\"num\":6,\"name\":\"早餐\",\"value\":\"无早\"}],\"tipData\":[{\"num\":1,\"name\":\"退订说明|退订说明\",\"value\":[{\"num\":1,\"name\":\"1\",\"value\":\"订单确认后无法操作变更，预订人非因法定原因取消，将扣收全额预付款作为违约金。（“法定原因”以《合同法》和《消费者权益保护法》规定为准，一般包括自然灾害、政府征用、酒店方过错等导致预订人不能正常入住的情形。）\"}]}],\"hotel\":{\"hotelPayTypeCode\":\"0\",\"hotelCityName\":\"北京\",\"hotelId\":\"2487602\",\"hotelName\":\"莫泰连锁酒店北京立水桥地铁站店\",\"hotelSeq\":\"beijing_city_25134\",\"hotelProductType\":5,\"supplier_id\":\"468467\",\"supplier_name\":\"莫泰连锁酒店北京立水桥地铁站店\",\"hotelCoupon\":\"0.00\",\"hotelCheckInDate\":\"20160617000000\",\"hotelCheckOutDate\":\"20160618000000\",\"slaveHotel\":{\"hotelAddress\":\"北京朝阳区安定门外立水桥北8号\",\"hotelCountry\":\"中国\",\"hotelLevel\":\"LEVEL1_ECONOMICAL\",\"hotelProvince\":\"北京\"},\"hotelCustomerNames\":[{\"hotelCustomerName\":\"xue\",\"hotelCertType\":\"NI\"}],\"hotel_Device\":{\"hotelUid\":\"tc_df6bd68124647481_154e07b4201_d33f\",\"hotelGid\":\"tc_df6bd68124647481_154e07b4201_d33f\",\"hotelVid\":\"91010000\",\"hotelPid\":\"10060\",\"hotelCookie\":\"tc_df6bd68124647481_154e07b4201_d33f\"},\"hotel_Client\":{\"hotelRoom_name\":\"特惠双人房\",\"hotelRoom_amount\":\"1\",\"hotelArrival_time\":\"17:00:00\",\"hotel_UserIp\":\"192.168.19.105\",\"hotelCreate_date\":\"20160617154828\",\"hotelBooking_channel\":\"MOBILE\"},\"hotel_Agent\":{\"hotelSupplier_id\":\"468467\"},\"hotel_Invoice\":{\"hotelSupplier_id\":\"468467\"},\"hotelOrderType\":\"0\"},\"contactName\":\"xue\",\"contactEmail\":\"\",\"contactPhone\":\"150o2l51867\",\"longPreAuth\":\"0\",\"hotelOrderType\":0}",
		"usedStarTickets": 0.0,
		"ifCheckInCashBack": false,
		"payMode": 0,
		"ifCheckOut": false,
		"errMtns": {"pageto": -1},
		"payStatusCode": 10,
		"otaInfo": {
			"wrapperId": "wapqunarqta",
			"otaLogo": "http://source.qunar.com/site/images/wap/otalogo/640-zhixiao.png",
			"otaPhone": "",
			"domain": "otaqta.qmp.qunar.com",
			"otaName": "去哪儿直销-预付"
		},
		"ifShowAccount": false,
		"ifPay": false,
		"invoiceEditOption": "NO_OPTION",
		"sysCode": "1005"
	},
	"isBookingWrapper": false,
	"checheUrl": "http://cheche.qunar.com/?sphone=9ba96d8dcd0518a9a80595a613b6d4b7&sname=a5c913a6babb2d54b96bbff818a40fb5&phonemsg=&seq=beijing_city_25134&gohotel=莫泰连锁酒店北京立水桥地铁站店&gocity=北京&sourceOrderId=100840718600&sourceDeliverType=0&sourceType=1&from=27"
};
var req =  {
	"wrapperId": "wapqunarqta",
	"sn": "",
	"refer": 0,
	"token": "a73d659be9fd4636be1be2141f1ef3b8",
	"orderNum": "100840718600",
	"opType": -1,
	"mcsign": "",
	"type": 0,
	"telephone": "15010451867",
	"smobile": "",
	"vcode": "",
	"mobile": ""
};

module.exports = {
	cookie: "测试cookie",
	commonParam: commonParam,
	commonParamStr: JSON.stringify(commonParam),
	dataStr: JSON.stringify(data),
	data: data,
	reqStr: JSON.stringify(req),
	req: req,
	ret: true
};